### ISSUE TITLE
Android Studio 2.2 Could not find method buildConfigString() for arguments

### ISSUE THREAD

**Issue by iturricf** [novoda/gradle-build-properties-plugin#14]
I've updated my build.gradle file to include gradle-build-properties-plugin. Then I tried to load some secrets into my debug buildType and got this message:

`Error:(46, 0) Could not find method buildConfigString() for arguments [MY_SECRET_KEY, com.novoda.buildproperties.Entry@249d2bfe] on BuildType_Decorated{name=debug, debuggable=true, testCoverageEnabled=false, jniDebuggable=false, pseudoLocalesEnabled=false, renderscriptDebuggable=false, renderscriptOptimLevel=3, minifyEnabled=false, zipAlignEnabled=true}, embedMicroApp=false, mBuildConfigFields={}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}} of type com.android.build.gradle.internal.dsl.BuildType`

Is anything that I'm doing wrong?

my build.gradle file:

```
buildscript {
    repositories {
        jcenter()
        maven { url 'https://maven.fabric.io/public' }
    }

    dependencies {
        classpath 'io.fabric.tools:gradle:1.22.1'
        classpath 'com.novoda:gradle-build-properties-plugin:0.3'
    }
}
apply plugin: 'com.android.application'
apply plugin: 'io.fabric'
apply plugin: 'com.novoda.build-properties'

...

android {
...

    buildProperties {
        secrets {
            file project.file('parameters.properties')
        }
    }

    buildTypes {
        debug {
            buildConfigString "MY_SECRET_KEY", buildProperties.secrets['a_secret_key'].or(buildProperties.env['MY_SECRET_KEY'])
       }
    }
...
```

**Comment by mr-archano** [comment]
Hi @iturricf, you have two options here:
- append a `.string` to fulfil the requirements of `buildConfigString` (it takes 2 `String`, one for the name of the field, the other will be used as value)
- use `buildConfigProperty` instead that will automatically convert the (lazily evaluated) chain of entries to `String` under the hood.

**Comment by iturricf** [comment]
@mr-archano thank you! tried with both approaches and it worked!

one more question.

what about `Properties inheritance` https://github.com/novoda/gradle-build-properties-plugin#properties-inheritance ? Is this a feature? How can I include another properties file?

**Comment by mr-archano** [comment]
@iturricf yes, properties inheritance is a feature. You can find an example in [the tests](https://github.com/novoda/gradle-build-properties-plugin/blob/master/plugin/src/test/groovy/com/novoda/buildproperties/FilePropertiesEntriesTest.groovy#L100-L111), where [`more.properties`](https://github.com/novoda/gradle-build-properties-plugin/blob/master/plugin/src/test/resources/more.properties) inherits from [`including.properties`](https://github.com/novoda/gradle-build-properties-plugin/blob/master/plugin/src/test/resources/including.properties), which in turn inherits [`any.properties`](https://github.com/novoda/gradle-build-properties-plugin/blob/master/plugin/src/test/resources/any.properties).

All you have to do is specify an `include` property with the relative path to the properties file you want to inherit from.

**Comment by tasomaniac** [comment]
I was looking that in samples but no success. We can add it to samples too.

**Comment by iturricf** [comment]
ohh now I see. I have to write the full filename. I was trying just the name without extensions.

thank you guys you're awesome!

would you like me to send a PR with property inheritance examples in README file?

**Comment by tasomaniac** [comment]
The plugin does not assume any file extension. So you have to always write the file path. 

Of course,  send it. It'd be awesome.

**Comment by mr-archano** [comment]
@iturricf PRs are always welcome! Thanks for the feedback :)
