### ISSUE TITLE
Declare presence of signing properties optional

### ISSUE THREAD

**Issue by johnjohndoe** [novoda/gradle-build-properties-plugin#16]
I do **not** want to require the presence of the `releaseSigning.properties` for my open source project in order to allow contributors to start using the project as quick as possible.

Currently, I am simply setting `android.buildTypes.release.signingConfig` to `null` as shown below:

``` groovy
File propFile = file("releaseSigning.properties");
if (propFile.exists()) {
    def Properties props = new Properties()
    props.load(new FileInputStream(propFile))

    if (props.containsKey("storeFile") &&
            props.containsKey("storePassword") &&
            props.containsKey("keyAlias") &&
            props.containsKey("keyPassword")
    ) {
        android.signingConfigs.release.storeFile = file(props["storeFile"])
        android.signingConfigs.release.storePassword = props["storePassword"]
        android.signingConfigs.release.keyAlias = props["keyAlias"]
        android.signingConfigs.release.keyPassword = props["keyPassword"]
    } else {
        android.buildTypes.release.signingConfig = null
    }
} else {
    android.buildTypes.release.signingConfig = null
}
```

How can I do the same with the _gradle-build-properties-plugin_?

**Comment by mr-archano** [comment]
Hi @johnjohndoe, I'm not sure the plugin can help simplifying the code above, given (at the moment) there is no support for checking keys in [`BuildProperties`](https://github.com/novoda/gradle-build-properties-plugin/blob/master/plugin/src/main/groovy/com/novoda/buildproperties/BuildProperties.groovy), altho this can be easily added.
You can try to create a custom [`Entries`](https://github.com/novoda/gradle-build-properties-plugin/blob/master/plugin/src/main/groovy/com/novoda/buildproperties/Entries.groovy) implementation and use that directly, I can try to draft something later.

Note that the support for Android signing configs came as afterthought and we were planning to remove it completely because not flexible enough (also it forces some public API in `BuildProperties` that doesn't make much sense to me).

**Comment by tasomaniac** [comment]
Here how I use this plugin to do optional signing config on my personal open source project. It is just 2 lines essentially.
https://github.com/tasomaniac/OpenLinkWith/blob/master/app/build.gradle#L8&L12

```
def signingFile = file('props/release.signing')
buildProperties {
    signing.file signingFile.exists() ? signingFile : file('props/debug.signing')
}
```

**Comment by johnjohndoe** [comment]
@tasomaniac Thanks for sharing. 
I tried your configuration but it still requires to add a `debug.signing` and a `debug.keystore` to the project. I would like to set the `release.signingConfig` to `null` if I don't want to compile a release.

@mr-archano 
> [...] Android signing configs [...] we were planning to remove it completely [...]

Oh! So I should jump on that horse, I guess.

**Comment by tasomaniac** [comment]
@johnjohndoe I agree it is not the same. :) Since I find providing a debug keystore in the repo is a good practice, this was not too bad.

**Comment by mr-archano** [comment]
Hey @johnjohndoe I put together something that should help in your case. It builds on top of the core functionality of the plugin without using `signingConfigProperties`. In your buildscript you would just amend the buildtypes adding a method that receives a `BuildProperties` instance and creates a signing config as you need (defaulting to `null` if any issue):

```gradle
buildProperties {
    release {
        file file('release.properties')
    }
}
...
android {
    ...
    buildTypes.all { buildType ->
        ext.optionalSigningConfig = { props ->
            try {
                def storeFile = props['storeFile'].string
                def storePassword = props['storePassword'].string
                def keyAlias = props['keyAlias'].string
                def keyPassword = props['keyPassword'].string
                def signingConfig = android.signingConfigs.create("$buildType.name") {
                    it.storeFile file(storeFile)
                    it.storePassword storePassword
                    it.keyAlias keyAlias
                    it.keyPassword keyPassword
                }
                buildType.signingConfig = signingConfig
            } catch (Exception e) {
                buildType.signingConfig = null
            }
        }
    }
    ...
    buildType {
        release {
            ...
            optionalSigningConfig buildProperties['release']
        }
    }
}
```
