### ISSUE TITLE
Remove `buildConfigProperty` and `resValueProperty`

### ISSUE THREAD

**Issue by mr-archano** [novoda/gradle-build-properties-plugin#17]
At the moment if the generated field/resource needs to have a different type than `String` the only option is to use typed accessors, eg:
```
buildConfigDouble 'RATE', buildProperties.bar['rate'].or{ 1.0 }.double
```
<br/>

It would be better if all the `buildConfig*` and `resValue*` utilities exposed by the plugin worked directly with `Entry` instances, eg:
```
buildConfigDouble 'RATE' buildProperties.bar['rate'].or { 1.0 }
```

This will incidentally make obsolete `buildConfigProperty` and `resValueProperty`, which implicitly convert any value to `String`.

**Comment by tasomaniac** [comment]
Fixed by #23
