### ISSUE TITLE
Can't use plugin in plain Java/Kotlin projects

### ISSUE THREAD

**Issue by frapontillo** [novoda/gradle-build-properties-plugin#3]
The plugin currently requires the Android Gradle plugin, failing if it's not there.

**Comment by mr-archano** [comment]
It's completely understandable to have the plugin working in not-Android projects, but this is the way it has been designed, so I wouldn't call a bug (even tho it bugs me too). I'll change it to `enhance`

**Comment by mr-archano** [comment]
#5 is shipped with a solution for the issue. @frapontillo let me know if this is enough!

**Comment by frapontillo** [comment]
It should be enough, much appreciated! 💯
