### ISSUE TITLE
Support absolute paths for keystore file

### ISSUE THREAD

**Issue by xrigau** [novoda/gradle-build-properties-plugin#31]
https://github.com/novoda/gradle-build-properties-plugin/blob/master/plugin/src/main/groovy/com/novoda/buildproperties/BuildPropertiesPlugin.groovy#L99

Currently the plugin appends the `storeFile` to the current working directory, but normally if the path starts with `/` that gets treated as absolute path and if it doesn't then it's treated as relative

It'd be nice if this was supported in the plugin

**Comment by mr-archano** [comment]
Support for keystores is planned to be removed as `0.4.0` (see https://github.com/novoda/gradle-build-properties-plugin/pull/24). I would suggest to avoid to use the built-in signing config support (easy to script in your project where you can make all the correct assumptions you need 💃 )

**Comment by xrigau** [comment]
fair enough! 👍
