### ISSUE TITLE
Add the plugin to Gradle Plugin repository

### ISSUE THREAD

**Issue by eximius313** [novoda/gradle-build-properties-plugin#37]
If you add your plugin to the [Gradle Plugin Repository](https://plugins.gradle.org/) then applying the plugin would be even easier:
```
plugins {
  id "build-properties" version "0.3"
}
```
and that's it - no need for additional `classpath` entries!

**Comment by mr-archano** [comment]
Thanks for the suggestion @eximius313. We are gonna start an internal discussion about using the Gradle Plugin Repository to publish our plugins. We'll keep you posted :)

**Comment by eximius313** [comment]
Any conclusions yet? :)

**Comment by tasomaniac** [comment]
@eximius313 Our static-analysis plugin is recently posted to the portal. https://github.com/novoda/gradle-static-analysis-plugin

We will probably do the same for this plugin too.

**Comment by eximius313** [comment]
Great! I'm eagerly waiting ;)

**Comment by mr-archano** [comment]
Addressed by #53
