### ISSUE TITLE
Missing readme example

### ISSUE THREAD

**Issue by blundell** [novoda/gradle-build-properties-plugin#4]
> More on loading properties

> If the specified file is not found an exception is thrown at build time as soon as one of its properties is evaluated. You can specify a custom error message to provide the user with more information.

An example of this is missing from the readme

**Comment by mr-archano** [comment]
Fixed in #5, see ["_More on loading properties_"](https://github.com/novoda/gradle-build-properties-plugin/blob/master/README.md#more-on-loading-properties) section in the `README`.
