### ISSUE TITLE
Create migration documentation

### ISSUE THREAD

**Issue by rock3r** [novoda/gradle-build-properties-plugin#50]
When moving from the old coordinates (`com.novoda:build-properties-plugin:1.2.1`) to the new ones (`com.novoda:gradle-build-properties-plugin:0.3.9`), there are significant hurdles to overcome. We should have a migration guide on what's changed so it's easier for people to migrate.

**Comment by mr-archano** [comment]
Yesterday I realised that the documentation in #52 basically covers part of the breaking changes introduced with `0.3.9` over previous versions of `com.novoda:gradle-build-properties-plugin`. One way of dealing with this is to mark the deprecated API and change the implementation to use the new API under the hood while providing some logs about the deprecation. The other is to improve the documentation to explicitly cover also the migration from `0.3.0` to `0.3.9+`

**Comment by eximius313** [comment]
https://github.com/novoda/gradle-build-properties-plugin/blob/master/docs/migrating-from-old-plugin.md
