### ISSUE TITLE
Clarify "using" syntax

### ISSUE THREAD

**Issue by ataulm** [novoda/gradle-build-properties-plugin#58]
The [docs](https://github.com/novoda/gradle-build-properties-plugin/blob/master/docs/advanced-usage.md) specify how you can reference properties files:

![image](https://user-images.githubusercontent.com/2678555/38759348-601cff10-3f6d-11e8-9387-2162d5d138c0.png)

but it says file is deprecated:

![image](https://user-images.githubusercontent.com/2678555/38759354-6c563cec-3f6d-11e8-8354-2a637bb8a625.png)

where clicking through seems to link to the wrong method?

![image](https://user-images.githubusercontent.com/2678555/38759412-bd7ab1a2-3f6d-11e8-8d0f-6fa37c766572.png)

```groovy
buildProperties {
    using letterboxd.properties
}
```

says could not find method `using()`

**How can I get rid of the deprecation warning?**

**Comment by rock3r** [comment]
I think it's a Gradle/Groovy bug where it thinks it's its own `file()` method, which is deprecated, instead of the `Project.file()` method you're actually calling. I think this is something @mr-archano is already aware of, seem to recall some discussions of it on Slack last week.

**Comment by ataulm** [comment]
:+1: ugh that's not :sunglasses: grooovy.

shall we transform this issue into that? or will it be time just to remove that method soon?

**Comment by mr-archano** [comment]
well, we can roll out a patch removing the annotation, you should get the big warning log in the console anyway, it's hard to miss 😅 
tiny PR? 😉
