### ISSUE TITLE
Unexpected fallback entries failure 

### ISSUE THREAD

**Issue by GabeMedrash** [novoda/gradle-build-properties-plugin#63]
Hi there,

After defining a fallback file source, my build immediately fails when the first file the plugin goes looking for does not exist. Have I misunderstood the purpose of [fallback entries](https://github.com/novoda/gradle-build-properties-plugin/blob/master/docs/advanced-usage.md#fallback-entries)? 

The following is my exact use case:
```
buildProperties {
    secrets {
        using(file("non-existent.file")).or(file("guaranteed-to-exist.file"))
    }
}
```

My expectation from the documentation is that if the plugin does not find "non-existent.file", it will load (or attempt to load) "guaranteed-to-exist.file". But, assuming I've debugged correctly, it [hits an immediate FileNotFound exception](https://github.com/novoda/gradle-build-properties-plugin/blob/master/plugin/src/main/groovy/com/novoda/buildproperties/internal/FilePropertiesEntries.groovy#L15).

Is this intentional behavior?

For reference, I am using version 0.4.1 taken from the Gradle Plugins Repository.

**Comment by mr-archano** [comment]
Ok @GabeMedrash I have spent some time looking into the issue you have raised and I actually can't reproduce the issue. I am using the same approach in one of my projects and it works as expected, if you want to take a look: [playground](https://github.com/mr-archano/playground/blob/fd353210954678e98619c68d21bb997dbc06b070/features/letterboxd/api/build.gradle#L8-L13)

What version of Gradle are you using? Would you be able to provide a sample project to reproduce the issue?

**Comment by GabeMedrash** [comment]
Ah, interesting. OK, so I created a Gist with a failing Gradle file: https://gist.github.com/GabeMedrash/93066236b3ebc2df10ffe42db23f70af.

Without the start task in the above referenced Gist (where `buildProperties` props are actually read), the build works. Once I try to read the values, though, I get the same `Build properties evaluation` failure about `...secrets.properties does not exist`, and that's using `project.file` or `new File(...)`. 

Using Java 1.8 and Gradle version 4.9.

Thanks!

**Comment by GabeMedrash** [comment]
Ah, thanks! Yes, I can confirm that changing the read of the buildProperties to something more straight forward--like below--works as expected:
```
task start(type: Exec) {
    environment([GITHUB_API_TOKEN: buildProperties.secrets['GITHUB_API_TOKEN'].string])
}
```
