### ISSUE TITLE
Support for yaml

### ISSUE THREAD

**Issue by eximius313** [novoda/gradle-build-properties-plugin#66]
Yaml is very popular format although it seems to not be supported by `gradle-build-properties-plugin`.
On the other hand, your plugin is awesome and I don't to stop using it, therefore I must stick to `.properties` format
Would you consider supporting `yaml` format as well?

**Comment by mr-archano** [comment]
Sure thing @eximius313, are you interested in contributing this feature? I have to confess I never used yaml from Gradle... any pointer would be appreciated!

**Comment by eximius313** [comment]
as you know `Yaml` is just a different way of storing properties. Instead of file with extension `.properties` you have file with extension `.yml` (and that is how you can differentiate them by the way).
That being said - it's just different format so both:
```
my.test=foo
my.tost=bar
other.test=baz
```
and
```
my:
  test: foo
  tost: bar
other:
  test: baz
```
will end up in exactly same properties map:
`[{my.test=foo}, {my.tost=bar}, {other.test=baz}]`

therefore the only change is to recognize the format by extension and instead of:
```
Properties prop = new Properties();
InputStream input = new FileInputStream("config.properties");
prop.load(input);
```
you use:
```
if(file.getName().endsWith(".yml")) {
  Yaml yaml = new Yaml();
  InputStream inputStream = new FileInputStream("config.yml");
  Map<String, Object> obj = yaml.load(inputStream);
}
```
see https://www.baeldung.com/java-snake-yaml

**Comment by tasomaniac** [comment]
One problem I foresee is that yaml is too flexible and it is not restricted to property map. It can contain other configuration like content. Do you think that is easy to handle?

**Comment by eximius313** [comment]
But here we are talking about situations where the intent is property map. Take Spring as an example. It's using `Properties` and `Yaml` interchangeably.

**Comment by juankysoriano** [comment]
Closing as this repository is no longer under maintenance and it's about to be archived
