### ISSUE TITLE
Moving away from jcenter() repo

### ISSUE THREAD

**Issue by boskicaruso** [novoda/gradle-build-properties-plugin#67]
Hi there,
Are there any plans to migrate from jcenter() while repo is sunsetting ? More info here: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by tasomaniac** [comment]
Hi, I don't think this plugin is maintained anymore. I wouldn't depend on it for the long term.

**Comment by dbrgn** [comment]
I replaced the plugin with the following Gradle snippet:

```groovy
def getLocalProperties() {
    final Properties props = new Properties()
    if (file('secrets.properties').exists()) {
        props.load(new FileInputStream(file('secrets.properties')))
    }
    return props
}

final Properties properties = getLocalProperties()
```

...then you can use `properties['key_name']` to access the values.

**Comment by juankysoriano** [comment]
Closing as this repository is no longer under maintenance and it's about to be archived
