### ISSUE TITLE
or support for signing configs

### ISSUE THREAD

**Issue by tasomaniac** [novoda/gradle-build-properties-plugin#7]
I was experimenting with the plugin on the weekend. 
`or` support works great for missing or optional prop files. But the signing configs does not support it. 

When my project is cloned, I want it to be immediately buildable. At least the debug build. 

So I fiddled with the plugin and added `or` support to the `file` method in `BuildProperties`. It worked quite well. I could go like this

```
    releaseSigning {
        file file('properties/releaseSigning.properties')
        or file('properties/debugSigning.properties')
    }
```

But I realized, it may not be really something we want. Comparing it with `include` and `or` support on `Entity`, it is only necessary for signing configs. 

So I'm thinking about working on `addSigningConfigSupportTo` to support alternatives configs if not found. 

What do you think?

**Comment by frapontillo** [comment]
What if you override the default method with `void file(File[] files, String errorMessage = null)` so the fallback is transparent to the main use case?

**Comment by tasomaniac** [comment]
File level there are multiple ways of doing it and that would mostly be easy. It could also be vararg of File s. 

I actually tried doing it. But I realized that it may not be parallel with the plugins intention. I think it make sense to assign 1 file to 1 object. 

With or on the entity you can get the value from different objects anyways. 

What do you think @mr-archano

**Comment by mr-archano** [comment]
To be honest I'm not sure about the whole support of signing config: it's a little bit flawed in the way files are resolved as relative paths to the properties file and (most annoying to me) it will work only **iff** the file will comply to the given structure, that makes things a little bit fragile.

That said I'll think about it and let you know soon(ish). We can catch up about this IRL if you prefer.

Thanks for the interest tho! 👍

**Comment by tasomaniac** [comment]
I agree. Also we have getParentFile in Entity object. Entity doesn't really need to know about files. It is only used for signing configuration support to access to the path to resolve the keystore full file path.

**Comment by tasomaniac** [comment]
I found a local solution like below to this situation

https://github.com/tasomaniac/OpenLinkWith/blob/master/app/build.gradle#L9

**Comment by mr-archano** [comment]
We haven't fully decided whether the signing config support will be removed. In the meantime I'm closing this issue because we agreed that `or` support for signing config is our of scope (but easily scriptable if needed).

**Comment by tasomaniac** [comment]
Here is how I did on [my personal project:](https://github.com/tasomaniac/OpenLinkWith/blob/master/app/build.gradle#L7) 

```
def signingFile = file('props/release.signing')
buildProperties {
    signing.file signingFile.exists() ? signingFile : file('props/debug.signing')
}
```
